server:
  port: 8099
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: 10MB  # 文件上传最大为10MB
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: dev
# 日志级别
logging:
  level:
    root: info

# 整合MyBatis
mybatis:
  type-aliases-package: com.imooc.pojo
  mapper-locations: classpath:mapper/*.xml

# 通用mapper工具的配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

# 分页插件助手的配置
pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true